const $=s=>document.querySelector(s), esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const skills=[["01","Systèmes & cloud","Windows Server, Linux, AD DS, DNS, DHCP, GPO, virtualisation et services."],["02","Réseaux & sécurité","TCP/IP, VLAN, routage, VPN, pfSense, Wireshark et sensibilisation."],["03","Support & ITSM","Diagnostic, GLPI, ITIL, gestion des incidents, parc et documentation."],["04","Automatisation & IA","n8n, API, IA générative, prompting et workflows pédagogiques."],["05","Ingénierie pédagogique","Progressions, cours, TP, MSP, examens, remédiation et évaluation."],["06","Services & supervision","Nextcloud, TrueNAS, Nagios, FreePBX, 3CX et auto-hébergement."]];
$("#skills").innerHTML=skills.map(x=>`<article class="skill-card"><span>${x[0]}</span><h3>${x[1]}</h3><p>${x[2]}</p></article>`).join("");
const tags=a=>`<div class="tags">${(a||[]).map(t=>`<span>${esc(t)}</span>`).join("")}</div>`;
let content;
function openModal(item,label){$("#modal-content").innerHTML=`<div class="gallery">${(item.images||[]).map((x,i)=>`<a href="${esc(x)}" target="_blank"><img src="${esc(x)}" alt="${esc(item.title)} — image ${i+1}"></a>`).join("")}</div><p class="eyebrow">${esc(label)}</p><h2>${esc(item.title)}</h2><p>${esc(item.detail||item.summary)}</p>${tags(item.tags)}${item.link?`<a class="button primary modal-link" href="${esc(item.link)}" target="_blank">${esc(item.linkLabel||"Accéder")} ↗</a>`:""}`;$("#modal").hidden=false;document.body.classList.add("locked")}
function render(){
 const engineering=content.engineering.filter(x=>x.visible).sort((a,b)=>a.position-b.position);
 $("#engineering-grid").innerHTML=engineering.map((x,i)=>`<article class="engineering-card card-${i+1}"><button class="media" data-kind="engineering" data-id="${esc(x.id)}"><img src="${esc(x.images[0]||"")}" alt="${esc(x.title)}">${x.images.length>1?`<span>${x.images.length} images</span>`:""}</button><div class="engineering-body"><span class="icon">${esc(x.icon)}</span><div><h3>${esc(x.title)}</h3><p>${esc(x.summary)}</p>${tags(x.tags)}<button class="text-button" data-kind="engineering" data-id="${esc(x.id)}">Voir les réalisations →</button></div></div></article>`).join("");
 const projects=content.projects.filter(x=>x.visible).sort((a,b)=>a.position-b.position);
 $("#project-grid").innerHTML=projects.map(x=>`<article class="project-card"><button class="media" data-kind="projects" data-id="${esc(x.id)}"><img src="${esc(x.images[0]||"")}" alt="${esc(x.title)}">${x.images.length>1?`<span>${x.images.length} images</span>`:""}</button><div class="project-content"><small>${esc(x.category)}</small><h3>${esc(x.title)}</h3><p>${esc(x.summary)}</p>${tags(x.tags)}<button class="text-button" data-kind="projects" data-id="${esc(x.id)}">Voir le projet →</button></div></article>`).join("");
 $("#custom-sections").innerHTML=(content.sections||[]).filter(x=>x.visible).sort((a,b)=>a.position-b.position).map(x=>`<section class="section shell custom"><div class="intro"><p class="eyebrow">${esc(x.category||"SECTION")}</p><h2>${esc(x.title)}</h2><p>${esc(x.summary)}</p></div>${x.images?.[0]?`<img src="${esc(x.images[0])}" alt="${esc(x.title)}">`:""}${x.link?`<a class="button secondary" href="${esc(x.link)}">${esc(x.linkLabel||"En savoir plus")} ↗</a>`:""}</section>`).join("");
 document.querySelectorAll("[data-kind]").forEach(b=>b.onclick=()=>openModal(content[b.dataset.kind].find(x=>x.id===b.dataset.id),b.dataset.kind==="projects"?"PROJET":"INGÉNIERIE PÉDAGOGIQUE"));
}
fetch("data/content.json",{cache:"no-store"}).then(r=>r.json()).then(d=>{content=d;render()}).catch(()=>{$("#project-grid").innerHTML="<p>Le contenu n’a pas pu être chargé.</p>"});
$(".close").onclick=()=>{$("#modal").hidden=true;document.body.classList.remove("locked")};$("#modal").onclick=e=>{if(e.target===e.currentTarget)$(".close").click()};document.addEventListener("keydown",e=>e.key==="Escape"&&$(".close").click());$(".menu").onclick=()=>document.querySelector("header nav").classList.toggle("open");$("#year").textContent=new Date().getFullYear();
